backend:
  name: git-gateway
  branch: master

media_folder: 'static/blog'
public_folder: '/blog'

collections:
  - name: 'blog' # Used in routes, e.g., /admin/collections/blog
    label: 'Blog' # Used in the UI
    folder: 'src/blogs' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{year}}-{{slug}}'
    fields:
      - { label: 'title', name: 'title', widget: 'string', required: true }
