backend:
  name: git-gateway
  branch: master

media_folder: 'static/blog'
public_folder: '/blog'

collections:
  - name: 'blog' # Used in routes, e.g., /admin/collections/blog
    label: 'Blog' # Used in the UI
    folder: 'src/blogs' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{month}}-{{day}}-{{year}}_{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Date', name: 'date', widget: 'date' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
